# Generated by Django 3.0.6 on 2020-05-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numberofplayersperteam',
            field=models.IntegerField(default='16'),
        ),
        migrations.AddField(
            model_name='profile',
            name='numberofteamsinleague',
            field=models.IntegerField(default='8'),
        ),
    ]
