# Generated by Django 3.0.6 on 2020-05-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200529_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='d',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='k',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qb',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rb',
            field=models.IntegerField(default='6'),
        ),
        migrations.AddField(
            model_name='profile',
            name='te',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wr',
            field=models.IntegerField(default='6'),
        ),
    ]
