# Generated by Django 3.0.6 on 2020-06-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200529_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='NflPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playersname', models.CharField(max_length=100)),
                ('playersteam', models.CharField(max_length=100)),
                ('playersposition', models.CharField(max_length=100)),
                ('forecastedpoints', models.IntegerField()),
            ],
        ),
    ]
