# Generated by Django 3.0.6 on 2020-06-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_nflplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflplayers',
            name='forecastedpoints',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
