# Generated by Django 3.0.6 on 2020-06-04 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200603_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='d',
            field=models.PositiveIntegerField(default='1', validators=[django.core.validators.MinValueValidator('1', message=None), django.core.validators.MaxValueValidator('8', message=None)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='k',
            field=models.PositiveIntegerField(default='1', validators=[django.core.validators.MinValueValidator('1', message=None), django.core.validators.MaxValueValidator('8', message=None)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numberofplayersperteam',
            field=models.PositiveIntegerField(default='16', validators=[django.core.validators.MinValueValidator('10', message=None), django.core.validators.MaxValueValidator('28', message=None)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numberofteamsinleague',
            field=models.PositiveIntegerField(default='8', validators=[django.core.validators.MinValueValidator('6', message=None), django.core.validators.MaxValueValidator('20', message=None)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qb',
            field=models.PositiveIntegerField(default='2', validators=[django.core.validators.MinValueValidator('1', message=None), django.core.validators.MaxValueValidator('8', message=None)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rb',
            field=models.PositiveIntegerField(default='6', validators=[django.core.validators.MinValueValidator('1', message=None), django.core.validators.MaxValueValidator('8', message=None)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='te',
            field=models.PositiveIntegerField(default='2', validators=[django.core.validators.MinValueValidator('1', message=None), django.core.validators.MaxValueValidator('8', message=None)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wr',
            field=models.PositiveIntegerField(default='6', validators=[django.core.validators.MinValueValidator('1', message=None), django.core.validators.MaxValueValidator('8', message=None)]),
        ),
    ]
