# Generated by Django 3.0.6 on 2020-06-13 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200603_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='d',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Enter A Greater than 0'), django.core.validators.MaxValueValidator(15, message='Enter A Number Equal To or Less Than 15')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='k',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Enter A Greater than 0'), django.core.validators.MaxValueValidator(15, message='Enter A Number Equal To or Less Than 15')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numberofplayersperteam',
            field=models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(10, message='Enter A Greater than or Equal to 10'), django.core.validators.MaxValueValidator(40, message='Enter A Number Equal To or Less Than 40')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numberofteamsinleague',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(6, message='Enter A Greater than or Equal to 6'), django.core.validators.MaxValueValidator(20, message='Enter A Number Equal To or Less Than 20')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qb',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1, message='Enter A Greater than 0'), django.core.validators.MaxValueValidator(15, message='Enter A Number Equal To or Less Than 15')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rb',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1, message='Enter A Greater than 0'), django.core.validators.MaxValueValidator(25, message='Enter A Number Equal To or Less Than 25')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='te',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1, message='Enter A Greater than 0'), django.core.validators.MaxValueValidator(25, message='Enter A Number Equal To or Less Than 25')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wr',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1, message='Enter A Greater than 0'), django.core.validators.MaxValueValidator(25, message='Enter A Number Equal To or Less Than 25')]),
        ),
    ]
