# Generated by Django 3.0.6 on 2020-07-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200613_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflplayers',
            old_name='playersname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nflplayers',
            old_name='forecastedpoints',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='nflplayers',
            old_name='playersposition',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='nflplayers',
            old_name='playersteam',
            new_name='team',
        ),
    ]
