# Generated by Django 3.0.6 on 2020-08-08 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersnflplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numberofplayersperteam',
            field=models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(10, message='Enter A Greater than or Equal to 10'), django.core.validators.MaxValueValidator(25, message='Enter A Number Equal To or Less Than 25')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numberofteamsinleague',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(6, message='Enter A Greater than or Equal to 6'), django.core.validators.MaxValueValidator(18, message='Enter A Number Equal To or Less Than 18')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qb',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Enter A Greater than 0'), django.core.validators.MaxValueValidator(15, message='Enter A Number Equal To or Less Than 15')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wr',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Enter A Greater than 0'), django.core.validators.MaxValueValidator(25, message='Enter A Number Equal To or Less Than 25')]),
        ),
    ]
