# Generated by Django 3.0.6 on 2020-06-23 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='draftstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='draft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
