# Generated by Django 3.0.6 on 2020-06-23 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draft', '0002_auto_20200623_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersNflPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playersname', models.CharField(max_length=100)),
                ('playersteam', models.CharField(max_length=100)),
                ('playersposition', models.CharField(max_length=100)),
                ('forecastedpoints', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='draft',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
