# Generated by Django 3.0.6 on 2020-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_auto_20200628_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickedplayers',
            name='season',
            field=models.IntegerField(default=2020),
        ),
    ]
