# Generated by Django 3.0.6 on 2020-06-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_auto_20200628_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickedplayers',
            name='forecastedpoints',
        ),
    ]
