# Generated by Django 3.0.6 on 2020-06-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0007_remove_pickedplayers_forecastedpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickedplayers',
            name='forecastedpoints',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
