# Generated by Django 3.0.6 on 2020-06-30 10:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draft', '0008_pickedplayers_forecastedpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draftposition', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Enter A Greater than or Equal to 1'), django.core.validators.MaxValueValidator(40, message='Enter A Number Equal To or Less Than 40')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
