# Generated by Django 3.0.6 on 2020-07-03 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0009_auto_20200630_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='NflPlayerPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='NflTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nflteams', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='pickedplayers',
            name='playersposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.NflPlayerPositions'),
        ),
        migrations.AlterField(
            model_name='pickedplayers',
            name='playersteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.NflTeams'),
        ),
    ]
