# Generated by Django 3.0.6 on 2020-07-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0010_auto_20200703_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedplayers',
            name='playersposition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pickedplayers',
            name='playersteam',
            field=models.CharField(max_length=100),
        ),
    ]
