# Generated by Django 3.0.6 on 2020-07-03 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0011_auto_20200703_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedplayers',
            name='playersposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.NflPlayerPositions'),
        ),
        migrations.AlterField(
            model_name='pickedplayers',
            name='playersteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.NflTeams'),
        ),
    ]
