# Generated by Django 3.0.6 on 2020-07-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0012_auto_20200703_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickedplayers',
            name='draftround',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
