# Generated by Django 3.0.6 on 2020-07-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0013_pickedplayers_draftround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedplayers',
            name='playersposition',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='pickedplayers',
            name='playersteam',
            field=models.CharField(max_length=3),
        ),
    ]
