# Generated by Django 3.0.6 on 2020-07-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0014_auto_20200704_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickedplayers',
            old_name='playersname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pickedplayers',
            old_name='forecastedpoints',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='pickedplayers',
            old_name='playersposition',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='pickedplayers',
            name='playersteam',
        ),
        migrations.AddField(
            model_name='pickedplayers',
            name='rosterteam',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickedplayers',
            name='team',
            field=models.CharField(max_length=3),
        ),
    ]
