# Generated by Django 3.0.6 on 2020-05-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftsettings',
            old_name='numberofteamsinLeague',
            new_name='numberofteamsinleague',
        ),
    ]
