# Generated by Django 3.0.6 on 2020-05-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200517_0759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DraftSettings',
            new_name='LeagueSettings',
        ),
    ]
