# Generated by Django 3.0.6 on 2020-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200517_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb', models.IntegerField()),
                ('rb', models.IntegerField()),
                ('wr', models.IntegerField()),
                ('te', models.IntegerField()),
                ('d', models.IntegerField()),
                ('k', models.IntegerField()),
            ],
        ),
    ]
