# Generated by Django 3.0.6 on 2020-05-23 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_leaguesettings_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesettings',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
