# Generated by Django 3.0.6 on 2020-05-23 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_leaguesettings_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguesettings',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='draftoptions',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='draftoptions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
