# Generated by Django 3.0.6 on 2020-06-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200523_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguesettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='DraftOptions',
        ),
        migrations.DeleteModel(
            name='LeagueSettings',
        ),
    ]
